# Generated by Django 4.2.6 on 2023-12-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kalyan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kalyan_Name', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('Kalyan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kalyan')),
            ],
        ),
    ]
