# Generated by Django 4.2.6 on 2023-12-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kalyan',
            old_name='Kalyan_Name',
            new_name='First_Name',
        ),
    ]
