# Generated by Django 4.2.6 on 2023-12-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_kalyan_name_kalyan_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sam',
            old_name='Kalyan_name',
            new_name='Fast_name',
        ),
    ]
