# Generated by Django 4.2.6 on 2023-12-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_kalyan_name_sam_fast_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sam',
            old_name='Fast_name',
            new_name='Fast_Name',
        ),
    ]
