# Generated by Django 4.2.6 on 2023-12-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_fast_name_sam_fast_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sam',
            old_name='Fast_Name',
            new_name='First_Name',
        ),
    ]
